/**
 * Comment Vote Domain Entity
 * 
 * Represents a user's vote on a comment (upvote/downvote).
 * Enforces one vote per user per comment with toggle capability.
 */

export type VoteType = 'upvote' | 'downvote' | 'report';

export interface CommentVoteEntity {
  id: string;
  commentId: string;
  userId: string;
  voteType: VoteType;
  votingReason: string | null;
  voteWeight: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateVoteInput {
  commentId: string;
  userId: string;
  voteType: VoteType;
  votingReason?: string | null;
  voteWeight?: number;
}

/**
 * Comment Vote Domain Logic
 */
export class CommentVote {
  private constructor(private readonly data: CommentVoteEntity) {}

  static create(input: CreateVoteInput): CommentVote {
    const entity: CommentVoteEntity = {
      id: '', // Generated by infrastructure
      commentId: input.commentId,
      userId: input.userId,
      voteType: input.voteType,
      votingReason: input.votingReason || null,
      voteWeight: input.voteWeight || 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    return new CommentVote(entity);
  }

  static fromPersistence(data: CommentVoteEntity): CommentVote {
    return new CommentVote(data);
  }

  // Domain methods
  changeVote(newVoteType: VoteType): void {
    this.data.voteType = newVoteType;
    this.data.updatedAt = new Date();
  }

  addReason(reason: string): void {
    this.data.votingReason = reason;
    this.data.updatedAt = new Date();
  }

  // Getters
  get id(): string {
    return this.data.id;
  }

  get commentId(): string {
    return this.data.commentId;
  }

  get userId(): string {
    return this.data.userId;
  }

  get voteType(): VoteType {
    return this.data.voteType;
  }

  get isUpvote(): boolean {
    return this.data.voteType === 'upvote';
  }

  get isDownvote(): boolean {
    return this.data.voteType === 'downvote';
  }

  get isReport(): boolean {
    return this.data.voteType === 'report';
  }

  toJSON(): CommentVoteEntity {
    return { ...this.data };
  }
}
