// HTTP status codes with type safety
export type { HttpStatusCode } from './http-status';
export {
  HTTP_STATUS_OK,
  HTTP_STATUS_CREATED,
  HTTP_STATUS_BAD_REQUEST,
  HTTP_STATUS_UNAUTHORIZED,
  HTTP_STATUS_FORBIDDEN,
  HTTP_STATUS_NOT_FOUND,
  HTTP_STATUS_INTERNAL_SERVER_ERROR,
  HTTP_STATUS_SERVICE_UNAVAILABLE,
  HTTP_STATUS_RANGES,
  isInformationalStatus,
  isSuccessStatus,
  isRedirectionStatus,
  isClientErrorStatus,
  isServerErrorStatus,
  isErrorStatus
} from './http-status';

// Time constants with type safety
export type { TimeDuration } from './time';
export {
  MILLISECONDS_PER_SECOND,
  MILLISECONDS_PER_MINUTE,
  MILLISECONDS_PER_HOUR,
  MILLISECONDS_PER_DAY,
  TIME_SECOND,
  TIME_MINUTE,
  TIME_HOUR,
  TIME_DAY,
  TIME_1S,
  TIME_5S,
  TIME_10S,
  TIME_30S,
  TIME_1M,
  TIME_5M,
  TIME_30M,
  TIME_1H,
  TIME_24H,
  SESSION_TIMEOUT_DEFAULT,
  TOKEN_EXPIRY_DEFAULT,
  CACHE_TTL_SHORT,
  CACHE_TTL_MEDIUM,
  CACHE_TTL_LONG,
  DB_TIMEOUT_SHORT,
  HTTP_TIMEOUT_SHORT,
  HTTP_TIMEOUT_MEDIUM,
  RETRY_DELAY_BASE,
  HEALTH_CHECK_INTERVAL,
  SHUTDOWN_TIMEOUT,
  secondsToMs,
  minutesToMs,
  hoursToMs,
  daysToMs,
  msToSeconds,
  msToMinutes,
  msToHours,
  msToDays
} from './time';