/**
 * Constitutional Provision Domain Entity
 * 
 * Represents a provision from Kenya's Constitution 2010.
 * Structured by: Chapter > Article > Section > Clause
 */

export interface ConstitutionalReference {
  chapter: number;
  article: number | null;
  section: number | null;
  clause: number | null;
}

export interface ConstitutionalProvisionEntity {
  id: string;
  
  // Constitutional hierarchy
  chapterNumber: number;
  articleNumber: number | null;
  sectionNumber: number | null;
  clauseNumber: number | null;
  
  // Content
  title: string;
  fullText: string;
  summary: string | null;
  
  // Legal classification
  isFundamentalRight: boolean; // Bill of Rights: Articles 19-59
  isDirectivePrinciple: boolean; // National Values: Article 10
  enforcementMechanism: 'judicial_review' | 'legislative_action' | 'administrative_action' | 'automatic' | null;
  
  // Relationships
  relatedProvisions: string[]; // IDs of related provisions
  keywords: string[];
  
  // Audit
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateProvisionInput {
  chapterNumber: number;
  articleNumber?: number | null;
  sectionNumber?: number | null;
  clauseNumber?: number | null;
  title: string;
  fullText: string;
  summary?: string | null;
  isFundamentalRight?: boolean;
  isDirectivePrinciple?: boolean;
  enforcementMechanism?: 'judicial_review' | 'legislative_action' | 'administrative_action' | 'automatic' | null;
  keywords?: string[];
}

/**
 * Constitutional Provision Domain Logic
 */
export class ConstitutionalProvision {
  private constructor(private readonly data: ConstitutionalProvisionEntity) {}

  static create(input: CreateProvisionInput): ConstitutionalProvision {
    const entity: ConstitutionalProvisionEntity = {
      id: '', // Generated by infrastructure
      chapterNumber: input.chapterNumber,
      articleNumber: input.articleNumber || null,
      sectionNumber: input.sectionNumber || null,
      clauseNumber: input.clauseNumber || null,
      title: input.title,
      fullText: input.fullText,
      summary: input.summary || null,
      isFundamentalRight: input.isFundamentalRight || false,
      isDirectivePrinciple: input.isDirectivePrinciple || false,
      enforcementMechanism: input.enforcementMechanism || null,
      relatedProvisions: [],
      keywords: input.keywords || [],
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    return new ConstitutionalProvision(entity);
  }

  static fromPersistence(data: ConstitutionalProvisionEntity): ConstitutionalProvision {
    return new ConstitutionalProvision(data);
  }

  // Domain methods
  addRelatedProvision(provisionId: string): void {
    if (!this.data.relatedProvisions.includes(provisionId)) {
      this.data.relatedProvisions.push(provisionId);
      this.data.updatedAt = new Date();
    }
  }

  removeRelatedProvision(provisionId: string): void {
    const index = this.data.relatedProvisions.indexOf(provisionId);
    if (index > -1) {
      this.data.relatedProvisions.splice(index, 1);
      this.data.updatedAt = new Date();
    }
  }

  addKeyword(keyword: string): void {
    const normalized = keyword.toLowerCase().trim();
    if (!this.data.keywords.includes(normalized)) {
      this.data.keywords.push(normalized);
      this.data.updatedAt = new Date();
    }
  }

  updateSummary(summary: string): void {
    this.data.summary = summary;
    this.data.updatedAt = new Date();
  }

  markAsFundamentalRight(): void {
    this.data.isFundamentalRight = true;
    this.data.updatedAt = new Date();
  }

  markAsDirectivePrinciple(): void {
    this.data.isDirectivePrinciple = true;
    this.data.updatedAt = new Date();
  }

  setEnforcementMechanism(mechanism: 'judicial_review' | 'legislative_action' | 'administrative_action' | 'automatic'): void {
    this.data.enforcementMechanism = mechanism;
    this.data.updatedAt = new Date();
  }

  // Getters
  get id(): string {
    return this.data.id;
  }

  get reference(): ConstitutionalReference {
    return {
      chapter: this.data.chapterNumber,
      article: this.data.articleNumber,
      section: this.data.sectionNumber,
      clause: this.data.clauseNumber,
    };
  }

  get referenceString(): string {
    let ref = `Chapter ${this.data.chapterNumber}`;
    if (this.data.articleNumber) ref += `, Article ${this.data.articleNumber}`;
    if (this.data.sectionNumber) ref += `, Section ${this.data.sectionNumber}`;
    if (this.data.clauseNumber) ref += `, Clause ${this.data.clauseNumber}`;
    return ref;
  }

  get isBillOfRights(): boolean {
    return this.data.isFundamentalRight && 
           this.data.articleNumber !== null && 
           this.data.articleNumber >= 19 && 
           this.data.articleNumber <= 59;
  }

  get isEnforceable(): boolean {
    return this.data.enforcementMechanism !== null;
  }

  get hasRelatedProvisions(): boolean {
    return this.data.relatedProvisions.length > 0;
  }

  matchesKeyword(keyword: string): boolean {
    const normalized = keyword.toLowerCase().trim();
    return this.data.keywords.some(k => k.includes(normalized) || normalized.includes(k));
  }

  toJSON(): ConstitutionalProvisionEntity {
    return { ...this.data };
  }
}
