/**
 * Constitutional Analysis Domain Entity
 * 
 * Represents an analysis of a bill's constitutional implications.
 * Can be automated (AI), expert-reviewed, or hybrid.
 */

export type AnalysisType = 'automated' | 'expert' | 'hybrid' | 'crowd_sourced';
export type ViolationType = 'direct_violation' | 'procedural_issue' | 'rights_infringement' | 'power_overreach' | 'ambiguity';

export interface PotentialViolation {
  provisionId: string;
  provisionReference: string;
  violationType: ViolationType;
  severity: 'critical' | 'high' | 'medium' | 'low';
  description: string;
  evidence: string[];
  confidence: number; // 0-1
}

export interface ConstitutionalAnalysisEntity {
  id: string;
  billId: string;
  
  // Analysis metadata
  analysisType: AnalysisType;
  confidenceScore: number; // 0-1
  
  // Constitutional implications
  provisionsC ited: string[]; // IDs of constitutional provisions
  potentialViolations: PotentialViolation[];
  
  // Expert review
  expertReviewRequired: boolean;
  expertReviewStatus: 'pending' | 'in_progress' | 'completed' | 'not_required';
  reviewedBy: string | null;
  reviewedAt: Date | null;
  expertNotes: string | null;
  
  // Analysis content
  summary: string;
  detailedAnalysis: string;
  recommendations: string[];
  
  // Audit
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateAnalysisInput {
  billId: string;
  analysisType: AnalysisType;
  confidenceScore: number;
  summary: string;
  detailedAnalysis: string;
  provisionsC ited?: string[];
  potentialViolations?: PotentialViolation[];
  recommendations?: string[];
}

/**
 * Constitutional Analysis Domain Logic
 */
export class ConstitutionalAnalysis {
  private constructor(private readonly data: ConstitutionalAnalysisEntity) {}

  static create(input: CreateAnalysisInput): ConstitutionalAnalysis {
    const entity: ConstitutionalAnalysisEntity = {
      id: '', // Generated by infrastructure
      billId: input.billId,
      analysisType: input.analysisType,
      confidenceScore: input.confidenceScore,
      provisionsC ited: input.provisionsC ited || [],
      potentialViolations: input.potentialViolations || [],
      expertReviewRequired: input.confidenceScore < 0.8 || (input.potentialViolations && input.potentialViolations.length > 0),
      expertReviewStatus: 'not_required',
      reviewedBy: null,
      reviewedAt: null,
      expertNotes: null,
      summary: input.summary,
      detailedAnalysis: input.detailedAnalysis,
      recommendations: input.recommendations || [],
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    // Set review status if required
    if (entity.expertReviewRequired) {
      entity.expertReviewStatus = 'pending';
    }

    return new ConstitutionalAnalysis(entity);
  }

  static fromPersistence(data: ConstitutionalAnalysisEntity): ConstitutionalAnalysis {
    return new ConstitutionalAnalysis(data);
  }

  // Domain methods
  addProvision(provisionId: string): void {
    if (!this.data.provisionsC ited.includes(provisionId)) {
      this.data.provisionsC ited.push(provisionId);
      this.data.updatedAt = new Date();
    }
  }

  addViolation(violation: PotentialViolation): void {
    this.data.potentialViolations.push(violation);
    this.data.expertReviewRequired = true;
    if (this.data.expertReviewStatus === 'not_required') {
      this.data.expertReviewStatus = 'pending';
    }
    this.data.updatedAt = new Date();
  }

  removeViolation(provisionId: string): void {
    this.data.potentialViolations = this.data.potentialViolations.filter(
      v => v.provisionId !== provisionId
    );
    this.data.updatedAt = new Date();
  }

  addRecommendation(recommendation: string): void {
    this.data.recommendations.push(recommendation);
    this.data.updatedAt = new Date();
  }

  startExpertReview(expertId: string): void {
    this.data.expertReviewStatus = 'in_progress';
    this.data.reviewedBy = expertId;
    this.data.updatedAt = new Date();
  }

  completeExpertReview(expertId: string, notes: string): void {
    this.data.expertReviewStatus = 'completed';
    this.data.reviewedBy = expertId;
    this.data.reviewedAt = new Date();
    this.data.expertNotes = notes;
    this.data.updatedAt = new Date();
  }

  updateConfidenceScore(score: number): void {
    if (score < 0 || score > 1) {
      throw new Error('Confidence score must be between 0 and 1');
    }
    this.data.confidenceScore = score;
    this.data.updatedAt = new Date();
  }

  // Getters
  get id(): string {
    return this.data.id;
  }

  get hasCriticalViolations(): boolean {
    return this.data.potentialViolations.some(v => v.severity === 'critical');
  }

  get hasHighSeverityViolations(): boolean {
    return this.data.potentialViolations.some(v => v.severity === 'high' || v.severity === 'critical');
  }

  get violationCount(): number {
    return this.data.potentialViolations.length;
  }

  get isHighConfidence(): boolean {
    return this.data.confidenceScore >= 0.8;
  }

  get needsExpertReview(): boolean {
    return this.data.expertReviewRequired && this.data.expertReviewStatus !== 'completed';
  }

  get isExpertReviewed(): boolean {
    return this.data.expertReviewStatus === 'completed';
  }

  get isAutomated(): boolean {
    return this.data.analysisType === 'automated';
  }

  get isExpertAnalysis(): boolean {
    return this.data.analysisType === 'expert' || this.data.analysisType === 'hybrid';
  }

  toJSON(): ConstitutionalAnalysisEntity {
    return { ...this.data };
  }
}
