#!/usr/bin/env tsx

/**
 * Shared Folder Auto-Fix Script
 * Generated by shared folder validation
 */

import { promises as fs } from 'fs';
import path from 'path';

async function fixSharedFolder(): Promise<void> {
  console.log('🔧 Applying shared folder fixes...');


  // Create missing index.ts for interfaces
  try {
    const indexPath = 'client\src\shared\interfaces\index.ts';
    const content = '// interfaces module exports\nexport * from \'.\';\n';
    await fs.writeFile(indexPath, content);
    console.log('✅ Created index.ts for interfaces');
  } catch (error) {
    console.warn('Failed to create index for interfaces:', error);
  }

  // Create missing index.ts for services
  try {
    const indexPath = 'client\src\shared\services\index.ts';
    const content = '// services module exports\nexport * from \'.\';\n';
    await fs.writeFile(indexPath, content);
    console.log('✅ Created index.ts for services');
  } catch (error) {
    console.warn('Failed to create index for services:', error);
  }

  // Create missing index.ts for types
  try {
    const indexPath = 'client\src\shared\types\index.ts';
    const content = '// types module exports\nexport * from \'.\';\n';
    await fs.writeFile(indexPath, content);
    console.log('✅ Created index.ts for types');
  } catch (error) {
    console.warn('Failed to create index for types:', error);
  }

  // Add missing export to client\src\shared\index.ts
  try {
    const content = await fs.readFile('client\src\shared\index.ts', 'utf-8');
    if (!content.includes('Add: export * from './types';')) {
      await fs.appendFile('client\src\shared\index.ts', '\nAdd: export * from './types';\n');
      console.log('✅ Added export to shared');
    }
  } catch (error) {
    console.warn('Failed to add export to shared:', error);
  }

  // Add missing export to client\src\shared\design-system\index.ts
  try {
    const content = await fs.readFile('client\src\shared\design-system\index.ts', 'utf-8');
    if (!content.includes('Add: export * from './primitives';')) {
      await fs.appendFile('client\src\shared\design-system\index.ts', '\nAdd: export * from './primitives';\n');
      console.log('✅ Added export to design-system');
    }
  } catch (error) {
    console.warn('Failed to add export to design-system:', error);
  }

  // Add missing export to client\src\shared\design-system\index.ts
  try {
    const content = await fs.readFile('client\src\shared\design-system\index.ts', 'utf-8');
    if (!content.includes('Add: export * from './utils';')) {
      await fs.appendFile('client\src\shared\design-system\index.ts', '\nAdd: export * from './utils';\n');
      console.log('✅ Added export to design-system');
    }
  } catch (error) {
    console.warn('Failed to add export to design-system:', error);
  }

  // Add missing export to client\src\shared\ui\index.ts
  try {
    const content = await fs.readFile('client\src\shared\ui\index.ts', 'utf-8');
    if (!content.includes('Add: export * from './education';')) {
      await fs.appendFile('client\src\shared\ui\index.ts', '\nAdd: export * from './education';\n');
      console.log('✅ Added export to ui');
    }
  } catch (error) {
    console.warn('Failed to add export to ui:', error);
  }

  // Add missing export to client\src\shared\ui\index.ts
  try {
    const content = await fs.readFile('client\src\shared\ui\index.ts', 'utf-8');
    if (!content.includes('Add: export * from './mobile';')) {
      await fs.appendFile('client\src\shared\ui\index.ts', '\nAdd: export * from './mobile';\n');
      console.log('✅ Added export to ui');
    }
  } catch (error) {
    console.warn('Failed to add export to ui:', error);
  }

  // Add missing export to client\src\shared\ui\index.ts
  try {
    const content = await fs.readFile('client\src\shared\ui\index.ts', 'utf-8');
    if (!content.includes('Add: export * from './navigation';')) {
      await fs.appendFile('client\src\shared\ui\index.ts', '\nAdd: export * from './navigation';\n');
      console.log('✅ Added export to ui');
    }
  } catch (error) {
    console.warn('Failed to add export to ui:', error);
  }

  // Add missing export to client\src\shared\ui\index.ts
  try {
    const content = await fs.readFile('client\src\shared\ui\index.ts', 'utf-8');
    if (!content.includes('Add: export * from './realtime';')) {
      await fs.appendFile('client\src\shared\ui\index.ts', '\nAdd: export * from './realtime';\n');
      console.log('✅ Added export to ui');
    }
  } catch (error) {
    console.warn('Failed to add export to ui:', error);
  }

  console.log('✅ Shared folder fixes applied!');
}

fixSharedFolder().catch(console.error);
