#!/usr/bin/env bash
# Phase 2 Test File Migration Generator
# Generates commands to migrate test files to colocated structure

WORKSPACE_ROOT="/c/Users/Access Granted/Downloads/projects/SimpleTool"
OUTPUT_FILE="$WORKSPACE_ROOT/phase2-migration-commands.sh"

{
  echo "#!/usr/bin/env bash"
  echo "# Phase 2: Test File Migration Commands"
  echo "# Generated by phase2-migration-generator.sh"
  echo "# "
  echo "# This script migrates test files to colocated structure"
  echo "# Run with: bash phase2-migration-commands.sh"
  echo ""
  echo "WORKSPACE_ROOT=\"$WORKSPACE_ROOT\""
  echo "echo 'Starting Phase 2 test file migration...'"
  echo ""
  
  echo "# =========================================="
  echo "# BATCH 1: Client Unit Tests - Colocate with Source"
  echo "# =========================================="
  echo ""
  
  # Find __tests__ directories in client and extract source files
  find "$WORKSPACE_ROOT/client/src" -type d -name "__tests__" | while read testdir; do
    component_dir=$(dirname "$testdir")
    component_name=$(basename "$component_dir")
    
    # Find all test files in this __tests__ directory
    find "$testdir" -maxdepth 1 -type f \( -name "*.test.tsx" -o -name "*.test.ts" \) | while read testfile; do
      testfile_name=$(basename "$testfile")
      
      # Generate move command
      echo "# Migrate: $testfile_name → $component_dir/"
      echo "if [ -f \"$testfile\" ]; then"
      echo "  mv \"$testfile\" \"$component_dir/$testfile_name\""
      echo "  echo '✓ Moved: $component_name/$testfile_name'"
      echo "fi"
      echo ""
    done
  done
  
  echo "# =========================================="
  echo "# BATCH 2: Client Integration Tests - Create __integration__"
  echo "# =========================================="
  echo ""
  
  find "$WORKSPACE_ROOT/client/src/components" -type d -name "__tests__" | while read testdir; do
    component_dir=$(dirname "$testdir")
    integration_dir="$component_dir/__integration__"
    
    echo "# Create integration directory: $integration_dir"
    echo "mkdir -p \"$integration_dir\""
    echo ""
    
    # Find integration test files (those with .integration. in name)
    find "$testdir" -maxdepth 1 -type f -name "*.integration.test.*" | while read testfile; do
      testfile_name=$(basename "$testfile")
      echo "mv \"$testfile\" \"$integration_dir/$testfile_name\""
    done
  done
  
  echo "# =========================================="
  echo "# BATCH 3: A11y Tests - Keep with Components"
  echo "# =========================================="
  echo ""
  
  find "$WORKSPACE_ROOT/client/src" -type d -name "__tests__" | while read testdir; do
    component_dir=$(dirname "$testdir")
    
    find "$testdir" -maxdepth 1 -type f -name "*.a11y.test.tsx" | while read testfile; do
      testfile_name=$(basename "$testfile")
      echo "# Move a11y test: $testfile_name → $component_dir/"
      echo "if [ -f \"$testfile\" ]; then"
      echo "  mv \"$testfile\" \"$component_dir/$testfile_name\""
      echo "  echo '✓ Moved: A11y test - $testfile_name'"
      echo "fi"
      echo ""
    done
  done
  
  echo "# =========================================="
  echo "# BATCH 4: Clean Up Empty __tests__ Directories"
  echo "# =========================================="
  echo ""
  echo "echo 'Cleaning up empty __tests__ directories...'"
  echo "find \"$WORKSPACE_ROOT/client/src\" -type d -name '__tests__' -empty -delete"
  echo ""
  
  echo "# =========================================="
  echo "# BATCH 5: Validation"
  echo "# =========================================="
  echo ""
  echo "echo 'Phase 2 migration complete!'"
  echo "echo 'Running tests to validate migration...'"
  echo "cd \"$WORKSPACE_ROOT\""
  echo "pnpm test -- --run 2>&1 | head -50"
  
} > "$OUTPUT_FILE"

chmod +x "$OUTPUT_FILE"
echo "✅ Generated migration commands: $OUTPUT_FILE"
echo ""
echo "Next steps:"
echo "1. Review the migration script: cat phase2-migration-commands.sh"
echo "2. Run the migration: bash phase2-migration-commands.sh"
echo "3. Fix any broken imports: pnpm run validate:imports"
echo "4. Run full test suite: pnpm test"
